# FlexASIO - https://github.com/dechamps/FlexASIO
# Enable low latency audio streaming for Windows based music production
# Use WASAPI as the PortAudio host API backend.
backend = "Windows WASAPI"
bufferSizeSamples = 128
