# Use WASAPI as the PortAudio host API backend.
backend = "Windows WASAPI"
bufferSizeSamples = 480

[input]
device = "Stereo Mix (Realtek High Definition Audio)"
channels = 2
suggestedLatencySeconds = 0.0
wasapiExclusiveMode = true

[output]
suggestedLatencySeconds = 0.0
wasapiExclusiveMode = false
